name = "imprimerie-sheets-creator"
compatibility_date = "2024-08-27"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm build"

[env.production]
name = "imprimerie-sheets-creator"

[env.production.vars]
# Environment variables will be set via Cloudflare dashboard or CLI
