import { Game, MTGSubCategory, SetOrigin, type GameFolders } from '../types/games';

const mtgFolders: GameFolders[] = [
  // By Main Groups

  {
    id: '1kCGCpmT8kzeLr-hQFcst3j8xRz_TKaVR',
    name: 'White',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1eeV8ZcKxdI0cmpPaiNUtTVDZ30Wqyv8J',
    name: 'Blue',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1TLvAHhoLl9qsX5LjcCFl6cTwLy0JLaau',
    name: 'Black',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1Vg54l0e1e2VP87pzISnNJB4cTIwqfS-R',
    name: 'Red',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1v0VgXpHLUiPEcDr-ltUV7ThgCdHRut_5',
    name: 'Green',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1VpBej2ooDWNPrVMEW8UnVDqm6qQprY33',
    name: 'Multicolors',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1rWbDlQTiMNl3G4dzcLPI6VX4Sa0QRdwC',
    name: 'Colorless',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1AZMJ7qKi_FaENH-eTxjov1N75Ux2e3vD',
    name: MTGSubCategory.LANDS,
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1PjofSLw0K1LCC36RtpnIQGd57qF_4lsp',
    name: 'Full Art Basic Lands',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1xY498X6PLCf7J-6Xyh9oVQSff49ilrMC',
    name: 'Normal Style Basic Lands',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1wvmV0zVn1Yann69IkBikkKJMcJyKZdYX',
    name: 'Retro Style Basic Lands',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1yOs420Hl5CkaNe3RzyOAVSYz9_FpCbor',
    name: MTGSubCategory.TOKENS,
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1HPuw0u6y0cvbId0JT8wqLfZp0sjdfbkc',
    name: 'Planechase',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1rjYhV-aBnxweDf_-La7pR-gPVpB6Acdc',
    name: 'FIN - FIC - FCA - SLD FF',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '16uXFPWJL67tFqBaarwMCEZxVovlFx1jd',
    name: 'MTG Standalone Crossovers',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1TRIuroBR8AMlYKOS_vLHMhqoTsmNtlvU',
    name: 'MTG Crossover: Dark Souls',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '15H5IwBV5NYchHNFPRYSO9m2IRCfHsuNy',
    name: 'MTG Crossover: Godzilla',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1-MNFrsCsbviQMAuUfiAKjKa138GncsMS',
    name: 'MTG Crossover: Heroes Of The Realm',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },
  {
    id: '1vHwLxtkP2UU6zfS0UGkcU40ZBGvtsqzh',
    name: 'MTG Crossover: The Walking Dead',
    bleed: 1,
    author: 'Magic The Gathring',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.MTG,
  },



  // Customs
  {
    id: '1ZC81zbzZHThYNDMlPR0GO6csTnKKsGLd',
    name: 'Adventure Time',
    bleed: 1,
    author: 'thefirstjakerowley',
    decklist: 'https://www.moxfield.com/decks/kmB3b-92wU-WaaUjPK1EGA',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1BJyzuwsE1P7wJjK8Fa2iMy0lKQnsjKPC',
    name: 'Adventure Time',
    bleed: 1,
    author: 'thefirstjakerowley',
    decklist: 'https://www.moxfield.com/decks/kmB3b-92wU-WaaUjPK1EGA',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '10LAS_3BlgVIjmuWw1RN5TDcK4AccMJvH',
    name: 'Arcane',
    bleed: 1,
    author: 'Haydensan',
    decklist: 'https://www.moxfield.com/decks/p2FZZDvV8E2pABH11Xs4Ww',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1QFLDSUQ-NV3ZYKirwDcCdvd-6VTe5T3o',
    name: 'Arcane',
    bleed: 1,
    author: 'Haydensan',
    decklist: 'https://www.moxfield.com/decks/p2FZZDvV8E2pABH11Xs4Ww',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '11-EiiN9ntMRqzYXG_wDBaCfiLb8KUYkX',
    name: 'Attack On Titan',
    bleed: 1,
    author: 'solomonsnewgrundle',
    decklist: 'https://drive.google.com/file/d/13m9RfPYRKU6kxM56RloNKR0YILf0WvJV/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '13m53ew9p92lIzdicHxwPrj7VG0EnMZ8t',
    name: 'Attack On Titan',
    bleed: 1,
    author: 'solomonsnewgrundle',
    decklist: 'https://drive.google.com/file/d/13m9RfPYRKU6kxM56RloNKR0YILf0WvJV/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '13rhBRrqMGnHTckGHHUdCM3zRCFar27UC',
    name: 'Avatar The Last Airbender - Customs',
    bleed: 1,
    author: '',
    decklist: 'https://archidekt.com/decks/7205651/atla_omnath_locus_of_creation',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '144pOlly71z5aa3_WkIKuclhoGBUFTj1D',
    name: 'Avatar The Last Airbender - Customs',
    bleed: 1,
    author: '',
    decklist: 'https://archidekt.com/decks/7205651/atla_omnath_locus_of_creation',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1I4WTf20zaf1Xq9A_k3tVYQNrERrRotcr',
    name: 'Batman',
    bleed: 1,
    author: 'Tortex',
    decklist: 'https://drive.google.com/file/d/1NHP_LTrjwoIauvikkvuGPqfWXVgoD6QX/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1Mr608-vhpqHOr5k14odjfw-M6xhhE_Da',
    name: 'Batman',
    bleed: 1,
    author: 'Tortex',
    decklist: 'https://drive.google.com/file/d/1NHP_LTrjwoIauvikkvuGPqfWXVgoD6QX/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1a4IB00QmWECR4xy6dey29WdrSkkr7GAg',
    name: 'Berserk - Griffith',
    bleed: 1,
    author: 'dnfire17',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1KOIYdGe3EoBSs3tG2L_ZfgDU1_jz9CNH',
    name: 'Berserk - Guts',
    bleed: 1,
    author: 'dnfire17',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1OlfQ4xgPKWo35C60s9MfDe0_oinPApMB',
    name: 'Berserk - Guts #2',
    bleed: 1,
    author: '2mescence',
    decklist: 'https://www.moxfield.com/decks/obwFjvNw0ES2gYrNviM58Q',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1jYBe5sANsuJbHM1pxPDSgRUyga7sGCJ9',
    name: 'Berserk - Guts #3',
    bleed: 1,
    author: '',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '133wggfTLPe5slsmuYKxPQfX2z7HQQFGo',
    name: 'Big Tech',
    bleed: 1,
    author: 'coderanger',
    decklist: 'https://moxfield.com/decks/TCAJzrlam0Cg54aOiEAVbw',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1NImm1QuYyranVmUiDF-BnwGfdFsYNoqC',
    name: 'Bleach',
    bleed: 1,
    author: 'TwistedTCG',
    decklist: 'https://tappedout.net/mtg-decks/isshin-kurosaki-bleach-deck-deck/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '16KApTcRd9gJ7OpWisBwgofYsE_xeEELi',
    name: 'Bloodborn',
    bleed: 1,
    author: 'bankaiyo123',
    decklist: 'https://www.moxfield.com/decks/xFUo0OhHhEi29HrqV2OhPQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '110b-T27pUkas9ZJNhdh2R9M-SfUKyy_x',
    name: 'Bloodborn',
    bleed: 1,
    author: 'bankaiyo123',
    decklist: 'https://www.moxfield.com/decks/xFUo0OhHhEi29HrqV2OhPQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1GwNUABZGFotDccurP9cTwXsKsaqWuFrS',
    name: 'Bloodborn - Umbris, Fear Manifest',
    bleed: 1,
    author: 'Zandaman',
    decklist: 'https://www.reddit.com/r/mpcproxies/comments/17o1z2q/bloodborne_reskin_full_proxy_edh_deck_for_umbris/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1TwhKrWSDotMwfIwemz8IZK_NtRM6wKEO',
    name: 'Borderlands',
    bleed: 1,
    author: 'HeyItsSpook',
    decklist: 'https://moxfield.com/decks/lrAHgyc1y0aBOMkzVcfB0A',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1Ki6OKJhEAPwhs-E7mLZ0VCQyygKT2G3k',
    name: 'Borderlands',
    bleed: 1,
    author: 'HeyItsSpook',
    decklist: 'https://moxfield.com/decks/lrAHgyc1y0aBOMkzVcfB0A',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '18MUCkTl40RWYHk1fYajR9FmBJXW-Ywzu',
    name: 'Borderlands',
    bleed: 1,
    author: 'HeyItsSpook',
    decklist: 'https://moxfield.com/decks/lrAHgyc1y0aBOMkzVcfB0A',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1dWXU342RDvITfLhWTKsMAcmmUFtuoJ03',
    name: 'Bunnies',
    bleed: 1,
    author: 'ReinetteHawke',
    decklist: 'https://www.moxfield.com/decks/JNCuwc2GC0yya_wiHACYbg',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1P70jmUD4a14NAv5PnlFBNn086kAV_FgM',
    name: 'Cats',
    bleed: 1,
    author: 'ukuleleaccordi',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SECRET_LAIR,
    game: Game.MTG,
  },
  {
    id: '16JEMgDblrKstENpAAVM0G2fNM9r5ri0R',
    name: 'Clair Obscur: Expedition 33',
    bleed: 1,
    author: 'Pascii20',
    decklist: 'https://moxfield.com/decks/AD-AsxvYykGabA3w-6IIjQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1hytsKJiusidSz_UrKTCuP478d_wuzPAG',
    name: 'Code Geass - Urza, Chief Artificer',
    bleed: 1,
    author: 'OctavioPrisca',
    decklist: 'https://docs.google.com/spreadsheets/d/1uElormP5pmoKNkJo7S37oMQ_68c9uwrK04ijjezPkuM/edit?gid=0#gid=0',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1PtGqVYyOjSAcwXnETLDLdn2kUfzO76Ex',
    name: 'Cyberpunk 2077',
    bleed: 1,
    author: 'pjohnson86',
    decklist: 'https://moxfield.com/decks/zn9A4oTL2UqMjP9NaBea5g',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1FJIDWORrDqToWMpPrpj-mEscLj9Ojqcm',
    name: 'Dark Souls - Isshin',
    bleed: 1,
    author: 'captainplanet52',
    decklist: 'https://manabox.app/decks/SrfEJy-wQ7u3oncFMqWeqg',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1IS7HNR93QJxYe1py79P1HEhvi4clJ9Y-',
    name: 'Dark Souls Isshin',
    bleed: 1,
    author: 'captainplanet52',
    decklist: 'https://manabox.app/decks/SrfEJy-wQ7u3oncFMqWeqg',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1xTpF5CCSzmMNPslwIJibn8HPbit6E_Zp',
    name: 'Dark Souls Isshin',
    bleed: 1,
    author: 'captainplanet52',
    decklist: 'https://manabox.app/decks/SrfEJy-wQ7u3oncFMqWeqg',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SIDEBOARD,
    game: Game.MTG,
  },
  {
    id: '1LEMOLVs2wt8dJECJQuuYNTnH9Dey8pV7',
    name: 'Dark Souls Isshin',
    bleed: 1,
    author: 'captainplanet52',
    decklist: 'https://manabox.app/decks/SrfEJy-wQ7u3oncFMqWeqg',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1VOyCYB3dQTX7ijIcLS_Oba9FcfEXHQfo',
    name: 'Diablo',
    bleed: 1,
    author: 'brosepolis',
    decklist: 'https://drive.google.com/file/d/1QpYpdtZIRVZtLGf0RFf0W-zFZXaWkLus/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1tfCQtu6PkD5L8ge46UWNftqQGqCEffx7',
    name: 'Diablo - Extras and Lands',
    bleed: 1,
    author: 'brosepolis',
    decklist: 'https://drive.google.com/file/d/1QpYpdtZIRVZtLGf0RFf0W-zFZXaWkLus/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SIDEBOARD,
    game: Game.MTG,
  },
  {
    id: '1no5ne9s_THaryjvqCVT_zhWpIO4dxaKS',
    name: 'Dr. Seuss',
    bleed: 1,
    author: 'Yugischmoe',
    decklist: 'https://tappedout.net/mtg-decks/dr-seuss-teller-of-tales-all-art-altered/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1rNwrrwVL7kDUSAB19y8TUplH4ldnefhF',
    name: 'Demon Slayer',
    bleed: 1,
    author: 'thetoastinside22',
    decklist: 'https://www.reddit.com/r/mpcproxies/comments/wy0lzm/finished_my_isshin_demon_slayer_deck_link_to_the/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1X1f25yY4febXVGWvs7ZvZDQF14UGS-ua',
    name: 'Demon Slayer',
    bleed: 1,
    author: 'thetoastinside22',
    decklist: 'https://www.reddit.com/r/mpcproxies/comments/wy0lzm/finished_my_isshin_demon_slayer_deck_link_to_the/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.BACKS,
    game: Game.MTG,
  },
  {
    id: '1tBw6Fv5RS83dXIIARksJppGVl0QaCcZ-',
    name: 'Demon Slayer',
    bleed: 1,
    author: 'thetoastinside22',
    decklist: 'https://www.reddit.com/r/mpcproxies/comments/wy0lzm/finished_my_isshin_demon_slayer_deck_link_to_the/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '14cjmgLwKGk784Erf3mZOoZojBN0Yv81w',
    name: 'Disney Princesses',
    bleed: 1,
    author: 'JRMJay00',
    decklist: 'https://www.moxfield.com/decks/_cJs10bxpkOeeF_hNZUDTA',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1mPkPZOlXiES55mIevyCelNmQHz0hIWFI',
    name: 'Dragon Quest',
    bleed: 1,
    author: 'canofbeams',
    decklist: 'https://old.reddit.com/r/mpcproxies/comments/1bara2e/deleted_by_user/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1lK2Zx2AfBpfed0Ezaqmk-qQp1YOE2Kuu',
    name: 'Dune - Hazezon, Shaper Of Sand',
    bleed: 1,
    author: 'DarksteelPenguin',
    decklist: 'https://imgur.com/a/enqn3gM',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1IofMWzXTAG0FskxMHaFtI5nTQ7Rwx1Kh',
    name: 'Dune - Rise of Muah\'Dib',
    bleed: 1,
    author: 'leocrevier',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1INwGpfgHY_862E_k4tItd5KJyNswjrva',
    name: 'Dune - Rise of Muah\'Dib',
    bleed: 1,
    author: 'leocrevier',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1-brEJjHJRhiUKjQxt4YycEQVtTRBlb-U',
    name: 'Dune - Baron',
    bleed: 1,
    author: 'Historical_Hamster54',
    decklist: 'https://www.archidekt.com/decks/7404813/baron_von_counters_final',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1eX2orjmYduRbAsP_6OGOw9WNhs4llrce',
    name: 'Dune - Baron',
    bleed: 1,
    author: 'Historical_Hamster54',
    decklist: 'https://www.archidekt.com/decks/7404813/baron_von_counters_final',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1zMXFrV7G_3jMDtBEX22QEyqkYtsf_x7P',
    name: 'Evangelion Neon Genesis Engine',
    bleed: 1,
    author: 'Apcebo',
    decklist: 'https://moxfield.com/decks/eEPgddXQ3UC8sYJU9hzfww',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1gleqe-oh3aMIZIloCqvJQwZnPQoBqyaJ',
    name: 'Evangelion Neon Genesis Engine Revamped',
    bleed: 1,
    author: 'Apcebo',
    decklist: 'https://moxfield.com/decks/eEPgddXQ3UC8sYJU9hzfww',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1JmoMR1vXjZJ5Ye9Hi72Zz2CUDAP5pVV-',
    name: 'Final Fantasy VII',
    bleed: 1,
    author: 'Apcebo',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1k34aBmpRhiLHeFHtp4rwaQGwg0wGJ5YF',
    name: 'Final Fantasy VII',
    bleed: 1,
    author: 'Apcebo',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1EAqEy5Hpb-DTOj1nUdwxHpnrBx7MexXH',
    name: 'Final Fantasy XIV - Y\'shtola Spellslinger',
    bleed: 0,
    author: 'Naraki_Maul',
    decklist: 'https://drive.google.com/file/d/1tFhyMv6SvKkjHrQjhToJj40zZL2lRJgl/view?usp=sharing',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1VSjBLu-F4tRAlXP2caIT162_kEFFTruy',
    name: 'Final Fantasy XIV - Tazri, Stalwart Survivor',
    bleed: 0,
    author: 'REMARKABLE',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1hcdyX7T-NwE4vsFy7N-M_c2Nnl1Uuck3',
    name: 'Final Fantasy XIV - Y\'shtola',
    bleed: 0,
    author: 'ELEMENT40',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1gDxdyD-AARSA2w_aPwhGItuV5bkDKRhC',
    name: 'Full Metal Alchemist',
    bleed: 1,
    author: 'TwistedTCG',
    decklist: 'https://www.twistedtcg.com/fmacommander',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1AIbNHtYkNHU1deXGHdVooW4J8l77ImGW',
    name: 'Frieren',
    bleed: 1,
    author: 'OctavioPrisca',
    decklist: 'https://docs.google.com/spreadsheets/d/1-zwdBCnswsJQmRPyKFWtRKSliTPJgxLBEljQSrfgavI/edit?gid=0#gid=0',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1OBesFl_TvabfHDDfu5NNjw58i_J_yYyu',
    name: 'Futurama',
    bleed: 1,
    author: 'SolomonsNewGrundle',
    decklist: 'https://drive.google.com/file/d/1OZbLcNS2pm-NpN4MMe78mVDljwkgz3LI/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1T3v-x6PNG25u5XDz5yn7FiOLGKy36Gsh',
    name: 'Gundam',
    bleed: 1,
    author: 'steggyface',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1YA9FCy-OzMRshLatfnad4CI9lK6bpruT',
    name: 'Game Of Thrones',
    bleed: 1,
    author: 'Apcebo',
    decklist: 'https://ko-fi.com/post/A-Game-of-Thrones-The-Long-Night-FULL-EDH-DECK-P5P3175W4P?justpublished=true&alias=A-Game-of-Thrones-The-Long-Night-FULL-EDH-DECK-P5P3175W4P#shareNewPostModal',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1ZaqHs2r36pjRgL9SzWVCT3gSsWJFGk1R',
    name: 'Goosebumps',
    bleed: 1,
    author: 'Okamihunter59',
    decklist: 'https://www.moxfield.com/decks/hUijkZ5zZUO_rPUuiRP_7A',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1koBmSc7U1Xlt8Qrz89HMEqfDVIPQ7Pfp',
    name: 'Gravity Falls',
    bleed: 1,
    author: 'Okamihunter59',
    decklist: 'https://www.moxfield.com/decks/Y8udIbJF506jBbRyogkz5w',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1R4f_2Yfp8R3wranN2ZdUgqWzF6HZAELX',
    name: 'Gravity Falls',
    bleed: 1,
    author: 'Okamihunter59',
    decklist: 'https://www.moxfield.com/decks/Y8udIbJF506jBbRyogkz5w',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1_TE_QAwBZ5c9-qAH16_QienBIBTUmdX2',
    name: 'Halo',
    bleed: 1,
    author: 'Helpful_Spell_5896',
    decklist: 'https://archidekt.com/decks/5857141/unsc',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1gSMDHjxxCe3yTqPZipH4pI6IJugoF0oD',
    name: 'Horizon',
    bleed: 1,
    author: 'thisishowtheworldsends',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1vECxWK6WJG6cqfOUc838-viNDB5pK68r',
    name: 'Jujutsu Kaisen - Narset, Enlighted Master',
    bleed: 1,
    author: 'OctavioPrisca',
    decklist: 'https://docs.google.com/spreadsheets/d/1pcEW8wmDdnssVqQECSpXPP2ZFw7LQknrq2mtzALjQxA/edit?gid=0#gid=0',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1QnrtLFx2rdblrwMwyu97B1f6GGfFCfgE',
    name: 'Kingdom Hearts',
    bleed: 1,
    author: 'Nerd of the Coast',
    decklist: 'https://deckstats.net/decks/163584/3212319-sora-s-power-of-friendshipi',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1B3UHTu7BYWig9U9LNJiAXDZoijIKLn5e',
    name: 'League of Legends',
    bleed: 0,
    author: 'Sakeretsu',
    decklist: '',
    origin: SetOrigin.CUSTOM,
    subCategory: MTGSubCategory.SECRET_LAIR,
    game: Game.MTG,
  },
  {
    id: '1g2WL28BRIf5D9r-ST0qrKkzU0bv-0a99',
    name: 'LoL - Star Guardians',
    bleed: 1,
    author: 'Bankaiyo123',
    decklist: 'https://www.moxfield.com/decks/pQaA9U96-Ey9UpMEdUa3YQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1V4erF7flOMB0_ThlaodwuHxLlp6S4DRQ',
    name: 'Star Guardians - LoL',
    bleed: 1,
    author: 'Bankaiyo123',
    decklist: 'https://www.moxfield.com/decks/pQaA9U96-Ey9UpMEdUa3YQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1iByFHeIvdA2BMYib-G9wXF9MZXomtniD',
    name: 'LoL - Star Guardians',
    bleed: 1,
    author: 'Bankaiyo123',
    decklist: 'https://www.moxfield.com/decks/pQaA9U96-Ey9UpMEdUa3YQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.ALTERNATIVES,
    game: Game.MTG,
  },
  {
    id: '1R7G80oxlX5W4jVR83TzG5tIpNg1TOSwt',
    name: 'Lovecraft',
    bleed: 1,
    author: 'Tortex',
    decklist: 'https://drive.google.com/file/d/1S4ZXuVw9Cr9Xm5H2MDx1eDH0YdZWB5jw/view',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1PuClUs53kMIm3Ar6w70N7QuaDHngMIzW',
    name: 'Marvel',
    bleed: 1,
    author: 'SeaMonkey',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1_F4AxBDX79Eut7XXm2tEHckfOPpLYAjY',
    name: 'Marvel',
    bleed: 1,
    author: 'SeaMonkey',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1JlFvcw11aeQ5T7iExjWt2uL4L-y_he2V',
    name: 'Marvel',
    bleed: 1,
    author: 'SeaMonkey',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1JNunCNkpc0lVKrx16iRuosH3xs8WeSqP',
    name: 'Marvel Rivals',
    bleed: 0,
    author: 'DingoXIII',
    decklist: 'https://moxfield.com/decks/GuS1gQ1wTUu8dVeHD23sDg',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1aYxXEjxTI2x2taevwLWzIUsHt1iAjtxI',
    name: 'Marvel Venom',
    bleed: 0,
    author: 'SolomonsNewGrundle',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SECRET_LAIR,
    game: Game.MTG,
  },
  {
    id: '1sczhh_R0I4ftNbZZ8uUuL7jGzQ8NOWK5',
    name: 'Monster Hunter',
    bleed: 1,
    author: 'Shei',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SECRET_LAIR,
    game: Game.MTG,
  },
  {
    id: '1U7mTLnUqCrQ_0QNUDgFpmdRsRGKYaV-M',
    name: 'Mass Effect',
    bleed: 1,
    author: 'ReinetteHawke',
    decklist: 'https://moxfield.com/decks/Jo0sgg1yg0idFj8JNPgYLQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '11LTM2n8djV0Ebt8LDMjqEtpvxoea0Lp-',
    name: 'Metal Gear Solid',
    bleed: 1,
    author: 'DarkVenusaur',
    decklist: 'https://moxfield.com/decks/796iswMLzkCtk_4aMfnA3Q',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1--yuNwnUtYBcKQpGqKz-wn7qK-nKdGP_',
    name: 'Metroid',
    bleed: 1,
    author: 'Genobyl',
    decklist: 'https://www.moxfield.com/decks/lBxzse4hNUOXM8Y1FvFnYA',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1Scvrk710igoxdgwOzSAt6e5yEDLecuSU',
    name: 'Metroid',
    bleed: 1,
    author: 'Genobyl',
    decklist: 'https://www.moxfield.com/decks/lBxzse4hNUOXM8Y1FvFnYA',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1ywTwANCK2MI5PDGNDODA0kU9QG3G6lbg',
    name: 'Metroid 2',
    bleed: 1,
    author: 'Arastelion',
    decklist: 'https://archidekt.com/decks/6864210/etrata_corrupting_influence',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1szyDwnhoDczhWH_ysGs7y806qhd5yKf6',
    name: 'Naruto',
    bleed: 1,
    author: 'PADANK',
    decklist: 'https://drive.google.com/file/d/1TR4Eo8Di9LmUwah3aY_wUzVMCGrq0mAb/view?usp=sharing',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1vc8qsDZVghz_n1jE1TKT8Iik1UQMARwE',
    name: 'Ninja Turtles',
    bleed: 1,
    author: 'bnm333',
    decklist: 'https://tappedout.net/mtg-decks/shadows-of-the-sewer/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1XIwcqcPO75NSkodsAIvVxLMEQlkmpDpE',
    name: 'Ninja Turtles',
    bleed: 1,
    author: 'bnm333',
    decklist: 'https://tappedout.net/mtg-decks/shadows-of-the-sewer/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1uJUksATfJ9i-9VsQESoSA2heHZFsxuv4',
    name: 'Ninja Turtles',
    bleed: 1,
    author: 'bnm333',
    decklist: 'https://tappedout.net/mtg-decks/shadows-of-the-sewer/',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SIDEBOARD,
    game: Game.MTG,
  },
  {
    id: '15-uQBsM-81s1fKTKTFjD4mzejCGDhBGY',
    name: 'Ninja Turtles',
    bleed: 1,
    author: 'jrmjay00',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1X1_ZL9vIJRppZTJnSVERatER6ImxYXBO',
    name: 'No Man\'s Sky',
    bleed: 1,
    author: 'Okamihunter59',
    decklist: 'https://www.moxfield.com/decks/O0G2eKFerkCR6sf1FDO-2A',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1ldV0zoPbUDvlvruKOz84tg21w8SXkAJ2',
    name: 'No Man\'s Sky',
    bleed: 1,
    author: 'Okamihunter59',
    decklist: 'https://www.moxfield.com/decks/O0G2eKFerkCR6sf1FDO-2A',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1-BUEaURvMKbrg3zG-8L6s9MLED-NLYKL',
    name: 'One Piece',
    bleed: 1,
    author: 'Nerd of the Coast',
    decklist: 'https://deckstats.net/decks/163584/3160980-luffy-s-ship',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1TXLRbPgTG1aC8ydnOmOA2zQ9vzy58G46',
    name: 'Over The Garden Wall',
    bleed: 1,
    author: 'Nicholas P. Reeve',
    decklist: 'https://www.moxfield.com/decks/nKeJPgQr_Umwhl2xgD_O_Q',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1nKoYGiDzUT1S2X7MvgfNHRuXvvHMZt3n',
    name: 'Over The Garden Wall',
    bleed: 1,
    author: 'Nicholas P. Reeve',
    decklist: 'https://www.moxfield.com/decks/nKeJPgQr_Umwhl2xgD_O_Q',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1emWiQ4aUSAFCXeVDIBhuSfX5H5YEr1m7',
    name: 'Pokemon',
    bleed: 1,
    author: 'Wayta',
    decklist: 'https://www.moxfield.com/decks/JiS5cdIcdUKAxnVRxDhmDQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1g5AJE3na_66iVhSOTsdGSPIawbWgOUy3',
    name: 'Pokemon',
    bleed: 1,
    author: 'Wayta',
    decklist: 'https://www.moxfield.com/decks/JiS5cdIcdUKAxnVRxDhmDQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.LANDS,
    game: Game.MTG,
  },
  {
    id: '1gFhcc1D84nzd3p1hoXzu_mYY39jxG5kn',
    name: 'Pokemon',
    bleed: 1,
    author: 'Wayta',
    decklist: 'https://www.moxfield.com/decks/JiS5cdIcdUKAxnVRxDhmDQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1ySHUyDshmx-hMINUnuc5SOg2G4mufVB3',
    name: 'Pokemon',
    bleed: 1,
    author: 'VitrousSpark',
    decklist: 'https://imgur.com/gallery/pokemon-proxy-mtg-11VnWgu',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1niE0gAJCn-8KK673Hv1Pdf4a2FRQfmV-',
    name: 'Power Rangers',
    bleed: 1,
    author: 'Nelynes',
    decklist: 'https://moxfield.com/decks/5uDftCcMU0qi_Cj1A3bnqQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1k-cSQO-sXNsxop4QbWMrfUA5x9t2OAkH',
    name: 'Power Rangers',
    bleed: 1,
    author: 'Nelynes',
    decklist: 'https://moxfield.com/decks/5uDftCcMU0qi_Cj1A3bnqQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SIDEBOARD,
    game: Game.MTG,
  },
  {
    id: '1Udxpf6VZ06b5d1hD3boMR_5CQ4pMWiXw',
    name: 'Power Rangers',
    bleed: 1,
    author: 'Nelynes',
    decklist: 'https://moxfield.com/decks/5uDftCcMU0qi_Cj1A3bnqQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1uLjUSI9xvVTmuULsbKgofkEGAR94mrJv',
    name: 'Sailor Moon',
    bleed: 0,
    author: 'N. B. Patenaude',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SECRET_LAIR,
    game: Game.MTG,
  },
  {
    id: '1bv8MQvInvtKV1EGfVGIQGkONcOY6rqjk',
    name: 'The Simpsons',
    bleed: 1,
    author: 'Tortex',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.SECRET_LAIR,
    game: Game.MTG,
  },
  {
    id: '1NgfIwS-1MPpmL63D2W3W20Q3T3qHq0Ei',
    name: 'Star Wars',
    bleed: 1,
    author: 'Mannywm4',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1qFcKeyjK3sQW68nEiIPMFziarU-tkcAh',
    name: 'Star Wars Separatists',
    bleed: 1,
    author: 'OOM-32',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1TvbK2AiB3RnguRuaFd7OExQulkv-wGkJ',
    name: 'Star Wars Separatists',
    bleed: 1,
    author: 'OOM-32',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1QPyd6Bz5tKHB79_HsYiN0Y5SRS5UrfUg',
    name: 'Scooby-Doo',
    bleed: 1,
    author: 'Initial-Ad107',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1IqlRc_AFprQgA9kVxAbQp_izvRlfJ-cc',
    name: 'Scooby-Doo',
    bleed: 1,
    author: 'Initial-Ad107',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1ySYtsOskDLPd5mGrxiqeiBMb9s6vQIvl',
    name: 'Solo Leveling',
    bleed: 1,
    author: 'Classy',
    decklist: 'https://www.moxfield.com/decks/nUib1wWRrU2UvGWAvBHZWQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1e7UAImMfIydQmRDZeVxcv6eGTCfbNPMG',
    name: 'Solo Leveling',
    bleed: 1,
    author: 'Classy',
    decklist: 'https://www.moxfield.com/decks/nUib1wWRrU2UvGWAvBHZWQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.ALTERNATIVES,
    game: Game.MTG,
  },
  {
    id: '1i_x3SAHWy7MtxKUYIQ4jRY5vxWDoy3K-',
    name: 'Solo Leveling',
    bleed: 1,
    author: 'Classy',
    decklist: 'https://www.moxfield.com/decks/nUib1wWRrU2UvGWAvBHZWQ',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1IOO0r4ZNzai9acDoi82x5wcxL-_mJ1zo',
    name: 'Spongebob',
    bleed: 1,
    author: 'TheChilisGuy',
    decklist: 'https://moxfield.com/decks/GBEMepmPyk--7Hv7yJfaDA',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1E4m0bsC4BJlSKEb8sDd9EVR7_ct-Hzfw',
    name: 'The Witcher',
    bleed: 1,
    author: 'Radabard',
    decklist: 'https://moxfield.com/decks/NBqPY-kQ_0Gzww_TCwSX-Q',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1EJyhQQWG_BPXxlVUYUCv3e5PJIXc1G1g',
    name: 'The Witcher - Francesca',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1sXUwmegCrK4mInCWlLphxg05cYzlm9C0',
    name: 'The Witcher - Francesca',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1Id2IQ_gCY_8rc4pXti-bev6YPE5oiI3b',
    name: 'The Witcher - Geralt',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1rNBMzo_eGlvoYaLBPVQIFxTivcg8Da-a',
    name: 'The Witcher - Geralt',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1WzFgoiYo6KKqSkyefdItV9CHM2XTkOV0',
    name: 'The Witcher - Monsters (Zerrikanterment)',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1WUd6RSIKMAne8daIO7KnTF8UDL5LUHyj',
    name: 'The Witcher - Monsters (Zerrikanterment)',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1pLoRqqFZf-vH6_CLv6drdKXtHsKVmYtH',
    name: 'The Witcher - Wild Hunt (Eredin)',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1NEyKbK83NG9p8WcGa8rKQjOuZnKb1ur-',
    name: 'The Witcher - Wild Hunt (Eredin)',
    bleed: 0,
    author: 'EVO-Atticus',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1T-2VA21IxeWmZW0a3FBm5oo4ogJnMvoc',
    name: 'World of Warcraft - The Lich King',
    bleed: 1,
    author: 'Havsglimt',
    decklist: 'https://drive.google.com/drive/folders/1StIByQZZN7KqOGqozY9hF4uqKaNEi-9v',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1HLw55UA0OrDKOoAMo99YzIDja94cg7M7',
    name: 'World of Warcraft - The Lich King - Islands',
    bleed: 1,
    author: 'Havsglimt',
    decklist: 'https://drive.google.com/drive/folders/1StIByQZZN7KqOGqozY9hF4uqKaNEi-9v',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1oDqz3UYHUJl567-sTZZrOPFuWbfisoCW',
    name: 'World of Warcraft - The Lich King - Mountains',
    bleed: 1,
    author: 'Havsglimt',
    decklist: 'https://drive.google.com/drive/folders/1StIByQZZN7KqOGqozY9hF4uqKaNEi-9v',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1xekzRiTmkh4DifWcSfwv6LKfzRZUaiGW',
    name: 'World of Warcraft - The Lich King - Swamp',
    bleed: 1,
    author: 'Havsglimt',
    decklist: 'https://drive.google.com/drive/folders/1StIByQZZN7KqOGqozY9hF4uqKaNEi-9v',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '16nOl9Hx-WbkZUm0BoDhC_r4qUtWoGiNO',
    name: 'World of Warcraft - The Lich King - Death Knights (9 needed)',
    bleed: 1,
    author: 'Havsglimt',
    decklist: 'https://drive.google.com/drive/folders/1StIByQZZN7KqOGqozY9hF4uqKaNEi-9v',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.DECK,
    game: Game.MTG,
  },
  {
    id: '1batPzfU7halyd0jg-qibXUmDXgj8L8Zy',
    name: 'World of Warcraft - The Lich King',
    bleed: 1,
    author: 'Havsglimt',
    decklist: 'https://drive.google.com/drive/folders/1StIByQZZN7KqOGqozY9hF4uqKaNEi-9v',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.TOKENS,
    game: Game.MTG,
  },
  {
    id: '1iXqkzhD0yaHDA6G0I4VxZbJJCXPpuLsz',
    name: 'YuGiOh - The Ur Dragon',
    bleed: 1,
    author: 'OctavioPrisca',
    decklist: 'https://docs.google.com/spreadsheets/d/1WnLD3WMFdlkHIH8dRmgK0HqYNcOS80Na1QcGPVQkSlI/edit?gid=0#gid=0',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1JxMbYspMsLPYPRhKIgMPrqCsNaAy6Kf3',
    name: 'Zelda - Breath Of The Wild',
    bleed: 0,
    author: 'nahdawgg',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1HGEpkDRz14bSdiszKZjSY5sENuG5SKMw',
    name: 'Zelda - Hyrule\'s Arsenal',
    bleed: 1,
    author: 'David E. Bass',
    decklist: 'https://moxfield.com/decks/xnaof2VFZk-SZss7mmy53Q',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
  {
    id: '1uBXgLRHC51No6yqtYu2eqfoD3Ha-9xBD',
    name: 'Zelda - Lore',
    bleed: 0,
    author: 'WhiteRabbitMTG',
    decklist: 'https://moxfield.com/decks/YlWDSTe49kSmkyFeqaP2Ng',
    origin: SetOrigin.PROXY,
    subCategory: MTGSubCategory.FULL_DECK,
    game: Game.MTG,
  },
];

const optcgFolders: GameFolders[] = [
  // Main Sets
  {
    id: '1tOGhsTi30uFBjA-Z4yFQ2P96sUqC8rr_',
    name: 'OP01',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1QHsAahiBFBJw4wVj2B8n2CN1OJc6BhBZ',
    name: 'OP01 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1Mh8cdH2Q4_Il4ARW8gWpTXddxxP-Qsfd',
    name: 'OP02',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1CSzV5sVx3cabI6TUn1g0XWruU8qNrKKe',
    name: 'OP02 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1gc1mi-aG-qBE4pCWYRM_c40BLHvset-g',
    name: 'OP03',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1_AIoTDbMQMP98mvfAetjG1Lk7sVyGNCV',
    name: 'OP03 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1CdUCV28gOWr7uAoZ2rVIwkuXhhIZX8sp',
    name: 'OP04',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1oAz7OZCb9Js6MWtGCWt1CDASGiJDAPzY',
    name: 'OP04 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1vbLcGPLj958nVwo7aODRLD2qswJdAXQf',
    name: 'OP05',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1jL2Cx6-46F9fLenyQ6V6diuid3pEN-mF',
    name: 'OP05 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1T9hvFDveNOROIIafdqnmpi5E5M52G9X1',
    name: 'OP05 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1--BAawNno0l-eAhM2NohJ7GVaa8j-2Ck',
    name: 'OP06',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '129oX9EaDK1vlji5F0ZiKuX4Nw0aR7BBC',
    name: 'OP06 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1CkVxwjCgX2CskUXr4ZUpiKn77cg3HCCU',
    name: 'OP06 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1JR-PHRPU-HXZ2VbVgF-L0fXuFKMb7U4e',
    name: 'OP06 TRs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1fiFnjC8bBLqSGhMAw0HYN_yxc0arPrNo',
    name: 'OP07',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '119KxxaECsKb7CeEVoCO8UTbe6fk84_-3',
    name: 'OP07 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '18K0BepZCCwFB5qUT__FS8e9e3oQu9ypG',
    name: 'OP07 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1UFONmnbBl063eSm6pLGDsjciG0irNwqc',
    name: 'OP07 TRs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1o9EPkf3eIYC4lvWc2Gck-0biyb5MV1NK',
    name: 'OP08',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1cW-ivmN4IQ1mq50iyKNtSsI-CLA70iJw',
    name: 'OP08 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1F2VcfNgtkZISTGfdvECR2tmpRyhbmv8k',
    name: 'OP08 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1d3zaF5zfJxVnKCy7oFylpH7IypgQ2XqA',
    name: 'OP09',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1AOysNJgl-k1MOyvyISlOOyF1Y5lHcqQI',
    name: 'OP09 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1ANrC0VbVgXH2FCI81KtJSULWQP3O2PPM',
    name: 'OP09 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1OqFhm9UKgOhbDOMHMxKGNgTtKnYEXq6-',
    name: 'OP10',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1kBFtSguUHKmEFaItERbqsnmyVdxtZzJf',
    name: 'OP10 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1q2m9744pPoyIA1FG8eiH_93fMgTNb63Q',
    name: 'OP10 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1TcsliNESunCVt-AOShceR64nX4sYXaoF',
    name: 'OP11',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1K3lkcWQJfwEFxv4TsO3KJ8ZZnSR0TGTz',
    name: 'OP11 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1N8deCs55bSYTyQPBHIrz9gpNhK9nmv0V',
    name: 'OP11 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1b5fBoKcl_j_951dw8v4DEDBC1V2ekB0X',
    name: 'OP12',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1v5Aaxl5LPsqzOrwF43bKesfQrWEtoJbY',
    name: 'OP12 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1QoTBoZyHEsFQMkP-I2xMSAJGFXmhSnk6',
    name: 'OP12 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '11OCtst5VqNhXuGzpRez-HnGwilTXMCSS',
    name: 'OP13',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1f8PRrd8kK5dy3GfO_Abn8bdYLdpAY9Xf',
    name: 'OP13 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1i6taSwaHku8VMRd1pRGiyXKSroHuk25Z',
    name: 'OP13 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1oxQcQ_AG246rbZnEnqArJhsMv3EKWmj8',
    name: 'OP14',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '14Qor0-ltr7z5CoAeDGDAWVfgk-dYPJHU',
    name: 'OP14 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },

  // Sub Sets
  {
    id: '1PaJQzsYrjlUW9bVF9Ivkwo4l_-l4vNYS',
    name: 'EB01',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1_2wGqtIdIR3BzsjGciHn-apERmcX8E1E',
    name: 'EB01 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '11fOuBoV1YmjA-sjAqWW41LciBZvg34ip',
    name: 'EB02',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1xODPK2EDZarV8RznosozDWibIo_oITHM',
    name: 'EB02 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '16AuCQApjwb_EVQypqXE7MvMj03ahJfOK',
    name: 'EB03',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1AGCmWBWy5F3sQpxn0dJCudtjp-pn5dwK',
    name: 'EB03 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1O7mqJGbW9Pnzi7pAprkhI2Ml5lwpogM5',
    name: 'EB03 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1u7QJoPE6WONDreN_XhCPIWS-aCfdEovs',
    name: 'EB03 Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '17QjGK-kMTmjsSzGa90g5kNHtFBYdOrIa',
    name: 'EB03 Gold Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1JOxl11iz3qzvuObGCbSKaxuB8sLCrdlT',
    name: 'EB04',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1AV2t8CA5do1S7xra7ORrJ4jZ38QsfmX1',
    name: 'EB04 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1cONwgutxS6u9yyZhPP3s-vOPIGiiEZXA',
    name: 'PRB01',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '13cM47xgCYg9Wf37qn1gsTxCKqcS-D5hn',
    name: 'PRB01 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1igwt2iatGGXna5CvI0XkFh3o_KQfPlQM',
    name: 'PRB01 Gold Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1yuUu3NZokAFo83aAkeQD0lGo2Exf7ye8',
    name: 'PRB02',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1qQW_vopy2dzMMzkYufek6IBauNkHYYQ3',
    name: 'PRB02 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '143iz5yQXYvVkipQFTEn7qsFB6T4GDacO',
    name: 'PRB02 SPs',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '17_IIzxZlKsJlCW_dtKPwcib1fpmmvZSC',
    name: 'PRB02 Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1WNfIRCag7dlZ41ZVjHpnK-8o6pe_wWhD',
    name: 'PRB02 Gold Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },

  // Starter decks
  {
    id: '14G4uNSDl8VjukWEAQPoyVbMkMOUZBTqV',
    name: 'ST01',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '176JafkoM5nlqnV1KDy5aaSZXfJVE67xj',
    name: 'ST01 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1YUNUBtCXHEA0x8EmZd5uGgJTCGbzrTDm',
    name: 'ST02',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1jjMeyydywY1ZUEcUrapFSI0lk1RDoJi2',
    name: 'ST02 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1a0YmUIcP-GwDoHlckgS1esIByQdxu2no',
    name: 'ST03',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1oMGMZFzDStt1rv9dpa0IOAF0c16kimP0',
    name: 'ST03 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1PhkEnQSjk42zzjT0pbabjkkOf58TLjXp',
    name: 'ST04',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1ligp9uAIBdA2i0oEyHRp9XhB6UxNyakD',
    name: 'ST04 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '12z-Y8g5Xdfy5UECMbFLrZBafqJNQ0NBe',
    name: 'ST05',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1jEjSrpcKrGLXNixjBu8BG7auWEPSTF0w',
    name: 'ST05 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '132--q2gpMnui1Q_mv6_Lq8P3Az8fZgWC',
    name: 'ST06',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '153ufQg8iZBD7Q67vDn1dVNhttv_CWc3f',
    name: 'ST06 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '13FgaO81gse_Ibm5cFpkB54WgUfuJET_K',
    name: 'ST07',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1y6yH5GTVpg8C1vKAfx_2aRyJD6bh_HfL',
    name: 'ST07 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '12Gp8x48id4QWVsuO6KViqVbmWgp8dJT5',
    name: 'ST08',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1AEPseOLGCeId0TtCevAKO1Viy-RoAN-z',
    name: 'ST08 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1EAzYrwLlbGGWogJaWDIDFFCpxwLXCPL_',
    name: 'ST09',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1QsKcTRbD5D3i-LNad6J1C9Ugu-FBTPb3',
    name: 'ST10',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '18fPoRwiuy_wbcuiuR93ZNp_uXM-CujLo',
    name: 'ST10 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '12XrMBcFW1QmfCneeT3qTIBv9pplBqUUS',
    name: 'ST11',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1QhoRzzG_Zg2zUvRTM_ZXpVAgZRHxM1id',
    name: 'ST11 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1oe1SGRhSsVnRjjrU7ODyQj-ChSsRF9eG',
    name: 'ST12',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1rjkOa2t6jQl3NbDiXR2kuUqCt-G7KNH_',
    name: 'ST12 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1DablZD1uq0_R6MBgrm34Vwm6aAC85Oze',
    name: 'ST13',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1iZ8Crmpn89VTbndqNrTL490bzN5LcjVF',
    name: 'ST13 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '17T3jTAzb6PFVurOCAAHrL0hHE-uG_CgO',
    name: 'ST14',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1SWYPHR5mX_KJReNE4RCIoHZ_W10G8zez',
    name: 'ST15',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1othQSQjuKLMrPOHaj2OxbjyOlffL_cqB',
    name: 'ST16',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1KgsBCmlbG5kUsqkBO1Kq1DhUXartyKLO',
    name: 'ST16 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '10hfC3P3gRiobL6kfZhMulOnotNfleEVk',
    name: 'ST17',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1jqa6xWNl6qptLUIJYh91booUHxUJvO8b',
    name: 'ST17 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1_xKXlRIO1WQrH6qI5f5fEBALZz0Xeilw',
    name: 'ST18',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1Iogy0hKVH0kQopYjS4enpQgdR_hU0yK1',
    name: 'ST19',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1kOquCtfXlQ6Ue8RSzPgAUwY9vfCUWwRT',
    name: 'ST20',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1dYrWB8PEqbrsbw6hDxVEj6eJP31wN7Za',
    name: 'ST21',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '10puThJtSgrb4qrA1M6GVBwAah3TIeqZG',
    name: 'ST21 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1w4MsPOecBbp-Boe_InTWHuU8KaH5nyIt',
    name: 'ST22',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '16RKWnGgWZQNLBkq4r5pAvw-7KS_WciBe',
    name: 'ST22 Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1UHI49i1xH5MJIwUfvZI0H2SLyVmG-ZkO',
    name: 'ST23',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1cFz1g0-7Tdv6WF0xwNQype9JFMz1_0Ng',
    name: 'ST24',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '10XDlpRNuZz5_qxhLGVAeLaV5U_2fAwCd',
    name: 'ST25',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1k8rrB8KqT6XcF7MHWyXvwy3xwtcVLNeV',
    name: 'ST26',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1zGWKGMaWDfXenOuvACOv0Kpy-Zchw98g',
    name: 'ST27',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1Y3U20ykH9FzmcbSGmkCZ_eluq_Daa1gZ',
    name: 'ST28',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },

  // Promoss
  {
    id: '13SlfwS0FFuqjSMjhxiXr3IhfKGYMefxC',
    name: 'OP06-10 Promos',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '14qU9tqCzhVfZPOhe_4UYm-JIqJxZy0k-',
    name: 'OP06-10 Promos Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1dYrWB8PEqbrsbw6hDxVEj6eJP31wN7Za',
    name: 'OP11+ Promos',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '10puThJtSgrb4qrA1M6GVBwAah3TIeqZG',
    name: 'OP11+ Promos Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },

  // Don!! folders
  {
    id: '1MBdQJHQqBhXkZCaHfJ9MGvsd14ZD2zdx',
    name: 'OP01-11 Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1yyuR8acsS7jVJOHNjuB6JsL8kfj6-8Hd',
    name: 'OP11+ Don!!',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },

  // Tournament cards
  {
    id: '1fWFeRHVn4-M6JHGvpHUxjF8-wPm22voF',
    name: 'Black Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1Qg_uaVS0MsRkuYHNg_lqVJDpasDJ59_w',
    name: 'Blue Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '13D7uLSvxkwyUb7AkL7dGfqhb-mCZkcCC',
    name: 'Green Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1OHeNKFakvGBhFik11maa-yWawYX7GOO9',
    name: 'Purple Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1lmMGEHgeO3b6vhXljsWgbXRrcHyUgdOt',
    name: 'Red Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1UOYCXnVfHsIJb_6gxHW5qVHANnWHlhTV',
    name: 'Yellow Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1eMIxcDvJ21S1Oj3dNqFnRHlJc0vhHJuF',
    name: 'Leaders Alts',
    bleed: 0,
    author: 'One Piece Card Game',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.OPTCG,
  },

  // Custom folders
  {
    id: '1eOmfpNGRE7jTnf5q9YetxvMiI7MTzr5r',
    name: 'OP TCG Custom Card Collection',
    bleed: 0,
    author: 'morpice0009',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1MZh9nG8oOBoa_OWAjxHlGviR9xvT7jpg',
    name: 'The Doctor\'s Customs',
    bleed: 0,
    author: 'Viri0x',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1XVRRnU4Y9ZB49XbDmbVhv1kcKyvhGFaZ',
    name: 'SadnessFML\'s Customs',
    bleed: 0,
    author: 'SadnessFML',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: null,
    game: Game.OPTCG,
  },
  {
    id: '1zgair1O1RTIjMV6yOU4MjAMWEljjhEyI',
    name: 'Baron Collection\'s Customs',
    bleed: 1,
    author: 'Baron Collection',
    decklist: '',
    origin: SetOrigin.PROXY,
    subCategory: null,
    game: Game.OPTCG,
  },
];

const riftboundFolders: GameFolders[] = [
  {
    id: '16-BXyrd0lGjy-4CB8K1arj9XeIq0PhSD',
    name: 'Riftbound Origins',
    bleed: 0,
    author: 'Riftbound',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.RIFTBOUND,
  },
  {
    id: '15X1UAp42k1gBA0_A1EwEtYDcH2iNHqFd',
    name: 'Riftbound Origins - Proving Grounds',
    bleed: 0,
    author: 'Riftbound',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.RIFTBOUND,
  },
];

const finalfantasyFolders: GameFolders[] = [
  {
    id: '1iIAFPR9deradYCB6LtDFakEkzp8vUFl7',
    name: 'Final Fantasy TCG',
    bleed: 0,
    author: 'Final Fantasy',
    decklist: '',
    origin: SetOrigin.OFFICIAL,
    subCategory: null,
    game: Game.FFTCG,
  },
];

export const gameFolders: GameFolders[] = [
  ...mtgFolders,
  ...optcgFolders,
  ...riftboundFolders,
  ...finalfantasyFolders,
];
